### ISSUE TITLE
Super work!

### ISSUE THREAD

**Issue by fracamil** [chrisroadmap/cop26-pathways#4]
@chrisroadmap Hello Chris,

What a wonderful work you've done!  Thanks a lot for this. It helps a lot seeing how FaIR v1.6 can be used to calculate mitigation scenario impact.

I did not know other mean to tell you how much this is useful: 
- for me (as an engineer who wants to be involved in climate evaluations about emissions mitigations in aviation;
- for the association Citoyens Pour Le Climat (Citizens for Climate, aka CPLC) in which I belong to the "Pôle Sciences" (scientific committee). Feel free to have a quick look at our works on https://citoyenspourleclimat.org/2019/03/24/posters-thematiques-kiosque-des-sciences/. 

Maybe there is a more appropriate channel to communicate but I don't know it...
 
A quick question, maybe not the right place: is contrail ERF taken into account in the AR6 calibrated configurations? I am not sure about it... If this question is not relevant here, can you please indicate me where it could be appropriate to ask it?

Best regards,

François

**Comment by chrisroadmap** [comment]
Hello @fracamil,

I'm really, really pleased you found this useful. Thank you for the feedback. It motivates me to keep putting code online!

In the AR6 calibrated projections, aviation contrails weren't included. The main reason is that the proxy emissions time series, emissions of NOx from the aviation sector, are not present in many of the scenarios that we will run FaIR for in the IPCC Working Group 3 assessment, so we have no way to estimate the impact. Contrail forcing was included however for the historical and SSP forcing and temperature projections in chapters 2, 4, 6 and 7 of Working Group 1, as the SSP scenarios did contain this level of detail and the aviation contrail forcing is formally assessed in this report.

All the best,
Chris

**Comment by fracamil** [comment]
Thank you very much for your answer. It helps me a lot. I will use the approach you use in this repository to estimate the aviation climatic impact (though i just read Dr. Lee did the same thing in an article). Anyway, I am glad to be able now to perform such simulations, thanks to you. 

Best regards, 
François
